# Generated by Django 5.2.5 on 2025-11-13 07:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_options_disike_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disike',
            new_name='Dislike',
        ),
    ]
